version: '3.8'

services:
  backend_rds:
    build:
      context: ./backend_rds
      dockerfile: Dockerfile
    container_name: custom_backend_rds  # Custom container name for backend_rds
    ports:
      - "8000:8000"  # Exposes backend_rds on port 8000
    env_file:
      - .env
    depends_on:
      - postgres

  backend_redis:
    build:
      context: ./backend_redis
      dockerfile: Dockerfile
    container_name: custom_backend_redis  # Custom container name for backend_redis
    ports:
      - "8001:8001"  # Exposes backend_redis on port 8001
    env_file:
      - .env
    depends_on:
      - redis
  postgres_custom:
    image: postgres:13
    container_name: postgres  # Custom container name for RDS (PostgreSQL)
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_custom:
    image: redis:latest
    container_name: redis  # Custom container name for Redis
    ports:
      - "6379:6379"
    environment: {}

volumes:
  postgres_data:
