version: '3.8'

services:
  backend_rds:
    build:
      context: ./backend_rds
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map backend_rds to port 8000
    env_file:
      - .env
    depends_on:
      - postgres

  backend_redis:
    build:
      context: ./backend_redis
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Map backend_redis to port 8001
    env_file:
      - .env
    depends_on:
      - redis

  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  postgres_data: