name: Deploy Docker Compose Services

on:
  push:
    branches:
      - main  # Adjust to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up SSH agent
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Add your private key in GitHub Secrets

    # Step 3: Copy project files to EC2
    - name: Copy Files to EC2
      run: |
        rsync -avz --exclude=".git" --exclude=".github" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/app/

    # Step 4: SSH into EC2 and deploy the Docker Compose stack
    - name: Deploy with Docker Compose
      run: |
        ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}/app
          docker-compose down
          docker-compose up -d --build
